<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{17d55ee0-0987-40b0-829c-2cffe93b08a6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[single.checkPower();
single.checkMoving();
single.checkRelMove();
single.checkHalt();
single.checkStop();
single.checkReset();
single.checkAdjustingVelocity();
single.checkSetPoint();
single.checkGoHome();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="621" Count="6" />
      <LineId Id="620" Count="0" />
      <LineId Id="632" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>