<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{4ca54771-8ae5-4549-901f-6cb523f28aef}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[master.dummyAction();
slave.dummyAction();

couple.checkGearIn();
couple.checkGearOut();

master.checkPower();
slave.checkPower();

master.checkSetPoint();
slave.checkSetPoint();


master.checkMoving();
master.checkRelMove();

master.checkReset();
master.checkStop();
master.checkGoHome();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="30" Count="1" />
      <LineId Id="9" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="39" Count="6" />
      <LineId Id="38" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>